from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak

out = Path(__file__).parent / 'private' / 'apostilas'; out.mkdir(parents=True, exist_ok=True)
styles=getSampleStyleSheet(); styles.add(ParagraphStyle('TitleJL',parent=styles['Title'],textColor=HexColor('#175ea8'),fontSize=28,leading=34,spaceAfter=20)); styles.add(ParagraphStyle('H',parent=styles['Heading2'],textColor=HexColor('#175ea8'),spaceBefore=14,spaceAfter=8)); styles['BodyText'].leading=16
def build(filename,title,subtitle,chapters):
    story=[Paragraph('JL Code',styles['TitleJL']),Paragraph(title,styles['TitleJL']),Paragraph(subtitle,styles['BodyText']),Spacer(1,18),Paragraph('Como estudar',styles['H']),Paragraph('Leia cada capítulo, reproduza os exemplos no seu editor e resolva os exercícios antes de avançar. Programação se aprende construindo.',styles['BodyText'])]
    for h,body,example,exercise in chapters:
      story += [PageBreak(),Paragraph(h,styles['H']),Paragraph(body,styles['BodyText']),Spacer(1,8),Paragraph('<b>Exemplo</b><br/>'+example,styles['BodyText']),Spacer(1,8),Paragraph('<b>Pratique</b><br/>'+exercise,styles['BodyText'])]
    doc=SimpleDocTemplate(str(out/filename),pagesize=A4,rightMargin=2*cm,leftMargin=2*cm,topMargin=2*cm,bottomMargin=2*cm,title=title,author='JL Code'); doc.build(story)
build('html-fundamentos.pdf','HTML do básico ao avançado','Apostila do Plano Beta', [('Módulo 1 - Estrutura','HTML organiza o conteúdo de uma página. Use html, head e body para criar uma base previsível.','&lt;h1&gt;Olá, mundo!&lt;/h1&gt;','Crie uma página com título e três parágrafos.'),('Módulo 2 - Textos, links e imagens','Use títulos em ordem, texto alternativo em imagens e links com descrição clara.','&lt;img src="foto.jpg" alt="Aluno estudando"&gt;','Monte uma página de perfil com imagem e links.'),('Módulo 3 - Formulários e tabelas','Labels associadas aos campos tornam formulários acessíveis. Tabelas são para dados.','&lt;label for="email"&gt;E-mail&lt;/label&gt;','Crie um formulário de contato validável.'),('Módulo 4 - Semântica e projeto','header, main, section, article e footer explicam a estrutura para pessoas e leitores de tela.','&lt;main&gt;&lt;article&gt;Conteúdo&lt;/article&gt;&lt;/main&gt;','Construa uma página de portfólio semântica.')])
build('css-interface.pdf','CSS do básico ao avançado','Apostila exclusiva do Plano Pro', [('Módulo 1 - Seletores e box model','CSS define apresentação. Todo elemento possui conteúdo, padding, borda e margem.','p { color: #175ea8; margin: 16px; }','Estilize os textos da sua página HTML.'),('Módulo 2 - Flexbox e Grid','Flexbox organiza uma dimensão; Grid é excelente para linhas e colunas.','display: grid; grid-template-columns: repeat(3, 1fr);','Crie uma grade de três cards.'),('Módulo 3 - Responsividade','Use media queries e dimensões flexíveis para telas menores.','@media (max-width: 700px) { .cards { grid-template-columns: 1fr; } }','Transforme sua grade em uma coluna no celular.'),('Módulo 4 - Transições','Transições reforçam feedback sem distrair.','button { transition: transform .2s; }','Adicione hover acessível a um botão.')])
build('javascript-pratica.pdf','JavaScript do básico ao avançado','Apostila exclusiva do Plano Pro', [('Módulo 1 - Variáveis e condições','Variáveis guardam valores. Condições escolhem caminhos do programa.','const idade = 18; if (idade >= 18) console.log("ok");','Mostre uma mensagem conforme uma nota.'),('Módulo 2 - Funções, arrays e objetos','Funções reutilizam lógica; arrays agrupam itens; objetos descrevem dados.','const aluno = { nome: "Ana", curso: "HTML" };','Liste três projetos usando um array.'),('Módulo 3 - DOM e eventos','O DOM permite selecionar e alterar a página após um evento.','botao.addEventListener("click", () => titulo.textContent = "Pronto");','Crie um contador com dois botões.'),('Módulo 4 - APIs e projeto','Fetch busca dados assíncronos. Trate erros para uma interface confiável.','const r = await fetch("/api/exemplo");','Crie uma busca de dados com estado de carregamento.')])
