import bcrypt from 'bcryptjs';

const plans = { BETA: { price: 12990 }, PRO: { price: 19990 } };
const json = (value, status = 200, headers = {}) => new Response(JSON.stringify(value), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...headers } });
const now = () => new Date().toISOString();
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const emailLayout = (content) => `<!doctype html><html lang="pt-BR"><body style="margin:0;background:#07111f;font-family:Arial,Helvetica,sans-serif;color:#eaf3ff"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;background:#0d1d33;border:1px solid #24476f;border-radius:18px;overflow:hidden"><tr><td align="center" style="padding:26px 24px 8px"><img src="https://jlcode.pages.dev/logo-jlcode.jpg" width="112" height="112" alt="JL Code" style="display:block;border-radius:56px;border:2px solid #2687ff"><h1 style="margin:16px 0 0;font-size:26px;color:#ffffff">JL Code</h1><p style="margin:6px 0 0;color:#66caff;font-weight:700;letter-spacing:1px;font-size:12px">CRIAR · APRENDER · EVOLUIR</p></td></tr><tr><td style="padding:22px 32px 34px;color:#dceaff;font-size:16px;line-height:1.6">${content}<p style="margin:28px 0 0;color:#9db2cc;font-size:13px">Se você não solicitou esta ação, pode ignorar este e-mail.</p></td></tr></table></td></tr></table></body></html>`;
function cookie(request, name) { return request.headers.get('cookie')?.split(';').map(x => x.trim()).find(x => x.startsWith(`${name}=`))?.slice(name.length + 1); }
function b64(data) { return btoa(String.fromCharCode(...new Uint8Array(data))).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''); }
function ub64(value) { const raw = atob(value.replaceAll('-','+').replaceAll('_','/') + '==='.slice((value.length + 3) % 4)); return Uint8Array.from(raw, c => c.charCodeAt(0)); }
async function sha(value) { return b64(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value))); }
async function key(secret) { return crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name:'HMAC', hash:'SHA-256' }, false, ['sign','verify']); }
async function sessionToken(id, secret) { const header=btoa('{"alg":"HS256","typ":"JWT"}').replaceAll('=',''); const body=btoa(JSON.stringify({sub:id,exp:Math.floor(Date.now()/1000)+604800})).replaceAll('=',''); const data=`${header}.${body}`; return `${data}.${b64(await crypto.subtle.sign('HMAC', await key(secret), new TextEncoder().encode(data)))}`; }
async function session(request, env) { try { const value=cookie(request,'jlcode_session'); if(!value) return null; const [a,b,s]=value.split('.'); if(!a||!b||!s||!(await crypto.subtle.verify('HMAC',await key(env.JWT_SECRET),ub64(s),new TextEncoder().encode(`${a}.${b}`)))) return null; const payload=JSON.parse(new TextDecoder().decode(ub64(b))); return payload.exp > Date.now()/1000 ? Number(payload.sub) : null; } catch { return null; } }
const lifetimeProEmails = new Set(['julianolucas004@gmail.com', 'furtadordosantos@gmail.com']);
async function user(env,id) {
  let account=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(id).first();
  if(!account || !lifetimeProEmails.has(String(account.email).toLowerCase())) return account;
  if(account.plan!=='PRO'||account.payment_status!=='CONFIRMED'||account.plan_ends_at!==null) {
    await env.DB.batch([
      env.DB.prepare("UPDATE users SET plan='PRO', payment_status='CONFIRMED', plan_started_at=COALESCE(plan_started_at, ?), plan_ends_at=NULL WHERE id=?").bind(now(),account.id),
      ...['HTML','CSS','JAVASCRIPT'].map(t=>env.DB.prepare("INSERT INTO accesses (user_id,course,technology,status) VALUES (?,?,?,'ACTIVE') ON CONFLICT(user_id,technology) DO UPDATE SET status='ACTIVE'").bind(account.id,t,t))
    ]);
    account=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(id).first();
  }
  return account;
}
function allowed(u) { return u.payment_status === 'CONFIRMED' ? u.plan === 'PRO' ? ['HTML','CSS','JAVASCRIPT'] : u.plan === 'BETA' ? ['HTML'] : [] : []; }
function publicUser(u) { return { id:u.id,name:u.name,email:u.email,plan:u.plan,paymentStatus:u.payment_status,allowedTechnologies:allowed(u),planStartedAt:u.plan_started_at,planEndsAt:u.plan_ends_at }; }
async function mail(env,to,subject,html) { if(!env.BREVO_API_KEY || !env.EMAIL_FROM) throw Error('O envio de e-mail não está configurado.'); const r=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'api-key':env.BREVO_API_KEY,'content-type':'application/json','accept':'application/json'},body:JSON.stringify({sender:{name:'JL Code',email:env.EMAIL_FROM},to:[{email:to}],subject,htmlContent:html})}); const data=await r.json().catch(()=>({})); if(!r.ok) throw Error(data.message || data.code || 'O Brevo recusou o envio.'); }
async function requireUser(context) { const id=await session(context.request,context.env); if(!id) return null; return user(context.env,id); }
async function createVerification(env,u,origin) { await env.DB.prepare('DELETE FROM email_verifications WHERE user_id=? AND used_at IS NULL').bind(u.id).run(); const token=crypto.randomUUID()+crypto.randomUUID(); await env.DB.prepare('INSERT INTO email_verifications (user_id,token_hash,expires_at) VALUES (?,?,?)').bind(u.id,await sha(token),new Date(Date.now()+86400000).toISOString()).run(); const link=`${origin}/api/auth/verify-email?token=${encodeURIComponent(token)}`; await mail(env,u.email,'Confirme seu cadastro — JL Code',emailLayout(`<p>Olá, ${escapeHtml(u.name)}.</p><p>Seu cadastro foi criado com sucesso. Confirme seu e-mail para ativar a sua conta:</p><p style="text-align:center;margin:28px 0"><a href="${link}" style="display:inline-block;background:#2687ff;color:#ffffff;text-decoration:none;border-radius:9px;padding:13px 22px;font-weight:700">CONFIRMAR MEU E-MAIL</a></p><p style="font-size:13px;color:#9db2cc">Este link é válido por 24 horas. Use sempre o botão do e-mail mais recente.</p>`)); }
function topic(message) { const text=message.toLowerCase(); if(/\b(css|flexbox|grid|stylesheet|estilo)/.test(text)) return 'CSS'; if(/\b(javascript|js\b|dom|array|função|funcao|variável|variavel)/.test(text)) return 'JAVASCRIPT'; return 'HTML'; }

async function createPasswordReset(env,u,origin) {
  await env.DB.prepare('DELETE FROM password_reset_tokens WHERE user_id=? AND used_at IS NULL').bind(u.id).run();
  const token=crypto.randomUUID()+crypto.randomUUID();
  await env.DB.prepare('INSERT INTO password_reset_tokens (user_id,token_hash,expires_at) VALUES (?,?,?)').bind(u.id,await sha(token),new Date(Date.now()+3600000).toISOString()).run();
  await mail(env,u.email,'Redefina sua senha — JL Code',emailLayout(`<p>Olá, ${escapeHtml(u.name)}.</p><p>Recebemos um pedido para redefinir a senha da sua conta JL Code.</p><p style="text-align:center;margin:28px 0"><a href="${origin}/redefinir-senha.html?token=${encodeURIComponent(token)}" style="display:inline-block;background:#2687ff;color:#ffffff;text-decoration:none;border-radius:9px;padding:13px 22px;font-weight:700">REDEFINIR MINHA SENHA</a></p><p style="font-size:13px;color:#9db2cc">Este link expira em uma hora e pode ser usado uma única vez.</p>`));
}

export async function onRequest(context) {
  const { request, env } = context; const url=new URL(request.url); const path=url.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean); const method=request.method; const body=method==='GET'||method==='HEAD'?{}:await request.json().catch(()=>({}));
  const auth=async()=>{ const u=await requireUser(context); return u || json({error:'Faça login para continuar.'},401); };
  try {
    if(method==='POST'&&path.join('/')==='auth/forgot-password') {
      const email=String(body.email||'').trim().toLowerCase();
      if(!/^\S+@\S+\.\S+$/.test(email)) return json({error:'Informe um e-mail válido.'},400);
      const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();
      if(u) await createPasswordReset(env,u,env.APP_URL||url.origin);
      return json({message:'Se este e-mail estiver cadastrado, você receberá um link para redefinir a senha.'});
    }
    if(method==='POST'&&path.join('/')==='auth/reset-password') {
      const token=String(body.token||''), password=String(body.password||'');
      if(!token||password.length<8||password!==body.confirmPassword) return json({error:'Use uma senha de pelo menos 8 caracteres e confirme-a corretamente.'},400);
      const reset=await env.DB.prepare('SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>?').bind(await sha(token),now()).first();
      if(!reset) return json({error:'Este link é inválido, já foi usado ou expirou.'},400);
      await env.DB.batch([
        env.DB.prepare('UPDATE users SET password_hash=? WHERE id=?').bind(await bcrypt.hash(password,12),reset.user_id),
        env.DB.prepare('UPDATE password_reset_tokens SET used_at=? WHERE id=?').bind(now(),reset.id)
      ]);
      return json({message:'Senha alterada com sucesso. Entre usando sua nova senha.'});
    }
    if(method==='POST'&&path.join('/')==='auth/register') { const name=String(body.name||'').trim(), email=String(body.email||'').trim().toLowerCase(), password=String(body.password||''); if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<8||password!==body.confirmPassword) return json({error:'Revise nome, e-mail e senha (mínimo de 8 caracteres).'},400); if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first()) return json({error:'Este e-mail já está cadastrado.'},409); const result=await env.DB.prepare('INSERT INTO users (name,email,password_hash) VALUES (?,?,?)').bind(name,email,await bcrypt.hash(password,12)).run(); const u=await user(env,result.meta.last_row_id); try { await createVerification(env,u,env.APP_URL||url.origin); } catch(error) { return json({error:`Conta criada, mas o e-mail não pôde ser enviado: ${error.message}`},502); } return json({message:'Cadastro criado. Confirme seu e-mail antes de entrar.'},201); }
    if(method==='GET'&&path.join('/')==='auth/verify-email') { const row=await env.DB.prepare('SELECT * FROM email_verifications WHERE token_hash=? AND used_at IS NULL AND expires_at>?').bind(await sha(url.searchParams.get('token')||''),now()).first(); if(!row) return new Response('Link inválido ou expirado.',{status:400}); await env.DB.prepare('UPDATE email_verifications SET used_at=? WHERE id=?').bind(now(),row.id).run(); return Response.redirect(`${url.origin}/login.html?verified=1`,302); }
    if(method==='POST'&&path.join('/')==='auth/resend-verification') { const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(String(body.email||'').trim().toLowerCase()).first(); if(!u) return json({message:'Se necessário, enviamos um novo e-mail de confirmação.'}); const verified=await env.DB.prepare('SELECT id FROM email_verifications WHERE user_id=? AND used_at IS NOT NULL').bind(u.id).first(); if(verified) return json({message:'Este e-mail já foi confirmado. Você já pode entrar.'}); await createVerification(env,u,env.APP_URL||url.origin); return json({message:'E-mail de confirmação reenviado. Confira a caixa de entrada e o spam.'}); }
    if(method==='POST'&&path.join('/')==='auth/login') { const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(String(body.email||'').trim().toLowerCase()).first(); if(!u||!(await bcrypt.compare(String(body.password||''),u.password_hash))) return json({error:'E-mail ou senha inválidos.'},401); if(!await env.DB.prepare('SELECT id FROM email_verifications WHERE user_id=? AND used_at IS NOT NULL').bind(u.id).first()) return json({error:'Confirme seu e-mail antes de entrar.'},403); const account=await user(env,u.id); const secure=url.protocol==='https:'?'; Secure':''; return json({user:publicUser(account)},200,{'set-cookie':`jlcode_session=${await sessionToken(u.id,env.JWT_SECRET)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${secure}`}); }
    if(method==='POST'&&path.join('/')==='auth/logout') return new Response(null,{status:204,headers:{'set-cookie':'jlcode_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'}});
    if(method==='POST'&&path.join('/')==='auth/forgot-password') return json({error:'A recuperação de senha será disponibilizada em breve.'},501);
    if(method==='GET'&&path.join('/')==='auth/me') { const u=await auth(); return u instanceof Response?u:json({user:publicUser(u)}); }
    if(method==='GET'&&path.join('/')==='plans') return json({plans:(await env.DB.prepare('SELECT * FROM plans ORDER BY id').all()).results});
    if(method==='POST'&&path.join('/')==='payments') { const u=await auth(); if(u instanceof Response)return u; const plan=String(body.plan||'').toUpperCase(), paymentMethod=String(body.method||'PIX').toUpperCase(); if(!plans[plan]||!['PIX','CARD'].includes(paymentMethod))return json({error:'Plano ou método de pagamento inválido.'},400); const transactionId=`JL-${crypto.randomUUID()}`; await env.DB.prepare('INSERT INTO payments (user_id,plan_code,amount_cents,method,transaction_id) VALUES (?,?,?,?,?)').bind(u.id,plan,plans[plan].price,paymentMethod,transactionId).run(); return json({transactionId,status:'PENDING',message:'Pagamento registrado como pendente. A liberação ocorre após a confirmação do provedor.'},201); }
    if(method==='POST'&&path[0]==='payments'&&path[2]==='confirm-demo') { const u=await auth(); if(u instanceof Response)return u; if(env.DEV_DEMO_MODE!=='true')return json({error:'Confirmação de demonstração desativada.'},403); const payment=await env.DB.prepare('SELECT * FROM payments WHERE transaction_id=? AND user_id=? AND status=?').bind(path[1],u.id,'PENDING').first(); if(!payment)return json({error:'Pagamento não encontrado.'},404); const start=now(), end=new Date(Date.now()+365*86400000).toISOString(); const tech=payment.plan_code==='PRO'?['HTML','CSS','JAVASCRIPT']:['HTML']; await env.DB.batch([env.DB.prepare("UPDATE payments SET status='CONFIRMED' WHERE id=?").bind(payment.id),env.DB.prepare("UPDATE users SET plan=?,payment_status='CONFIRMED',plan_started_at=?,plan_ends_at=? WHERE id=?").bind(payment.plan_code,start,end,u.id),...tech.map(t=>env.DB.prepare("INSERT INTO accesses (user_id,course,technology,status) VALUES (?,?,?,'ACTIVE') ON CONFLICT(user_id,technology) DO UPDATE SET status='ACTIVE'").bind(u.id,t,t))]); const updated=await user(env,u.id); mail(env,updated.email,`Pagamento confirmado — Plano ${payment.plan_code==='BETA'?'Beta':'Pro'} JL Code`, `<p>Olá, ${escapeHtml(updated.name)}.</p><p>Seu pagamento foi confirmado e seu plano está ativo.</p><p><a href="${env.APP_URL||url.origin}/aluno.html">ACESSAR ÁREA DO ALUNO</a></p>`).catch(console.error); return json({user:publicUser(updated)}); }
    if(method==='GET'&&path.join('/')==='student') { const u=await auth(); if(u instanceof Response)return u; return json({user:publicUser(u),accesses:(await env.DB.prepare('SELECT technology,status FROM accesses WHERE user_id=?').bind(u.id).all()).results}); }
    if(method==='GET'&&path[0]==='apostilas'&&path.length===1) { const u=await auth(); if(u instanceof Response)return u; const items=(await env.DB.prepare('SELECT a.slug,a.title,a.description,a.required_plan,c.name course,COALESCE(ua.progress_percent,0) progress_percent FROM apostilas a JOIN courses c ON c.id=a.course_id LEFT JOIN user_apostila_access ua ON ua.apostila_id=a.id AND ua.user_id=? ORDER BY a.id').bind(u.id).all()).results; return json({apostilas:items.map(x=>({...x,allowed:allowed(u).length>0&&(u.plan==='PRO'||x.required_plan==='BETA'&&u.plan==='BETA')}))}); }
    if(method==='GET'&&path[0]==='apostilas'&&path[2]==='pdf') { const u=await auth(); if(u instanceof Response)return u; const a=await env.DB.prepare('SELECT * FROM apostilas WHERE slug=?').bind(path[1]).first(); if(!a)return json({error:'Apostila não encontrada.'},404); if(!(u.plan==='PRO'&&u.payment_status==='CONFIRMED'||u.plan==='BETA'&&u.payment_status==='CONFIRMED'&&a.required_plan==='BETA'))return json({error:'Esta apostila não está liberada para o seu plano.'},403); const object=await env.APOSTILAS.get(`apostilas/${a.private_filename}`,{range:request.headers}); if(!object)return json({error:'Material em preparação.'},503); await env.DB.prepare('INSERT INTO user_apostila_access (user_id,apostila_id,progress_percent,last_opened_at) VALUES (?,?,5,?) ON CONFLICT(user_id,apostila_id) DO UPDATE SET progress_percent=MAX(progress_percent,5),last_opened_at=excluded.last_opened_at').bind(u.id,a.id,now()).run(); const headers=new Headers({'content-disposition':'inline','cache-control':'private, no-store','x-content-type-options':'nosniff'}); object.writeHttpMetadata(headers); return new Response(object.body,{headers,status:object.range?206:200}); }
    if(method==='GET'&&path.join('/')==='ai/history') { const u=await auth(); if(u instanceof Response)return u; const results=(await env.DB.prepare('SELECT message,response,created_at FROM ai_conversations WHERE user_id=? ORDER BY id DESC LIMIT 30').bind(u.id).all()).results.reverse(); return json({messages:results}); }
    if(method==='POST'&&path.join('/')==='ai/chat') { const u=await auth(); if(u instanceof Response)return u; const message=String(body.message||'').trim(), permitted=allowed(u), t=topic(message); if(!message||message.length>4000)return json({error:'Envie uma pergunta de até 4.000 caracteres.'},400); if(!permitted.length)return json({error:'Seu acesso à IA Gabriela está bloqueado. Assine um plano para liberar o acesso.'},403); if(!permitted.includes(t))return json({error:`Seu plano libera somente ${permitted.join(', ')}.`},403); if(!env.AI)return json({error:'IA not configured.'},503); const history=(await env.DB.prepare('SELECT message,response FROM ai_conversations WHERE user_id=? ORDER BY id DESC LIMIT 8').bind(u.id).all()).results.reverse(); const messages=[{role:'system',content:`Você é Gabriela, professora de programação para iniciantes. Responda apenas sobre ${permitted.join(', ')}; ensine passo a passo em português.`},...history.flatMap(x=>[{role:'user',content:x.message},{role:'assistant',content:x.response}]),{role:'user',content:message}]; const data=await env.AI.run('@cf/meta/llama-3.2-3b-instruct',{messages,max_tokens:700,temperature:0.35}); const answer=String(data.response||data.result?.response||'I could not generate an answer now.'); await env.DB.prepare('INSERT INTO ai_conversations (user_id,message,response,user_plan) VALUES (?,?,?,?)').bind(u.id,message,answer,u.plan).run(); return json({answer}); }
    return json({error:'Rota não encontrada.'},404);
  } catch(error) { console.error(error); return json({error:error.message||'Erro interno.'},500); }
}
